CREATE DATABASE ProfStudentQuiz;
CREATE TABLE Quiz (
 QuizId INT NOT NULL AUTO_INCREMENT,
 QuestionId INT NOT NULL,
 Questions VARCHAR(255) NOT NULL,
 Option VARCHAR(255) NOT NULL,
 CORRECT ANSWER VARCHAR(1)
 PRIMARY KEY (QuizId));
