USE ser516p2;
CREATE TABLE Quiz (
 QuizId INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
 QuestionId INT NOT NULL,
 Questions VARCHAR(255) NOT NULL,
 Options VARCHAR(255) NOT NULL,
 CORRECT_ANSWER VARCHAR(1)
 );
 
 DESCRIBE Quiz;
