CREATE TABLE QuizResultsRetired (
    StudentId           INT           PRIMARY KEY,
    QuizId              INT,
    QuestionId          INT,
    AnsId               INT,
    TimeTaken           INT,
    QuizCompletedOn     DATETIME,
    StudentTextComments VARCHAR (255),
    PointsScored        INT,
    FOREIGN KEY (
        QuizId,
        QuestionId,
        AnsId
    )
    REFERENCES QuizContent (QuizId,
    QuestionId,
    AnsId)
);
