CREATE TABLE quiz_content (
    quizId    INT     NOT NULL,
    quesId    INT     NOT NULL,
    quesType  VARCHAR DEFAULT SA
                      NOT NULL,
    quesDesc  TEXT    NOT NULL,
    ansId     INT     NOT NULL,
    ansDesc   TEXT    NOT NULL,
    isCorrect BOOLEAN NOT NULL,
    maxScore  INT     NOT NULL,
    CONSTRAINT quiz_content_pk PRIMARY KEY (
        quizId,
        quesId,
        ansId
    )
);
